version: "3"
services:
  pimon:
    image: php:7-apache
    container_name: pimon
    restart: always
    volumes:
      - ./web:/var/www/html
    command: "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apachectl restart && tail -f /dev/null'"
    command: "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo pdo_mysql && apachectl restart && tail -f /dev/null'"

networks:
  default:
    external:
      name: haproxy_default
